# Generated by Django 5.0.6 on 2024-06-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_total_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_attendees',
        ),
    ]
