# Generated by Django 5.0.6 on 2024-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_eventregistration_ticket_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.CharField(default='educational', max_length=150),
        ),
    ]
